# Chapter 14 Exercises

## Programming Exercises - Question 1

The textbook asks us to find a program named create cities database. Run the program. The program will create a database named The  database will have a table named , with the following columns. Then write a program that connects to the database, and allows the user to select any of the following operations:

In [17]:
import sqlite3

def main():
    # Connect to the database.
    conn = sqlite3.connect('cities.db')

    # Get a database cursor.
    cur = conn.cursor()
    
    # Add the Cities table.
    add_cities_table(cur)
    
    # Add rows to the Cities table.
    add_cities(cur)
    
    # Commit the changes.
    conn.commit()

    # Display the cities.
    display_cities(cur)
    
    # Close the connection.
    conn.close()

# The add_cities_table adds the Cities table to the database.
def add_cities_table(cur):
    # If the table already exists, drop it.
    cur.execute('DROP TABLE IF EXISTS Cities')

    # Create the table.
    cur.execute('''CREATE TABLE Cities (CityID INTEGER PRIMARY KEY NOT NULL,
                                        CityName TEXT,
                                        Population REAL)''')

# The add_cities function adds 20 rows to the Cities table.
def add_cities(cur):
    cities_pop = [(1,'Tokyo',38001000),
                  (2,'Delhi',25703168),
                  (3,'Shanghai',23740778),
                  (4,'Sao Paulo',21066245),
                  (5,'Mumbai',21042538),
                  (6,'Mexico City',20998543),
                  (7,'Beijing',20383994),
                  (8,'Osaka',20237645),
                  (9,'Cairo',18771769),
                  (10,'New York',18593220),
                  (11,'Dhaka',17598228),
                  (12,'Karachi',16617644),
                  (13,'Buenos Aires',15180176),
                  (14,'Kolkata',14864919),
                  (15,'Istanbul',14163989),
                  (16,'Chongqing',13331579),
                  (17,'Lagos',13122829),
                  (18,'Manila',12946263),
                  (19,'Rio de Janeiro',12902306),
                  (20,'Guangzhou',12458130)]
    
    for row in cities_pop:
        cur.execute('''INSERT INTO Cities (CityID, CityName, Population)
                       VALUES (?, ?, ?)''', (row[0], row[1], row[2]))

# The display_cities function displays the contents of
# the Cities table.
def display_cities(cur):
    print('Contents of cities.db/Cities table:')
    cur.execute('SELECT * FROM Cities')
    results = cur.fetchall()
    for row in results:
        print(f'{row[0]:<3}{row[1]:20}{row[2]:,.0f}')

# Execute the main function.
if __name__ == '__main__':
    main()

Contents of cities.db/Cities table:
1  Tokyo               38,001,000
2  Delhi               25,703,168
3  Shanghai            23,740,778
4  Sao Paulo           21,066,245
5  Mumbai              21,042,538
6  Mexico City         20,998,543
7  Beijing             20,383,994
8  Osaka               20,237,645
9  Cairo               18,771,769
10 New York            18,593,220
11 Dhaka               17,598,228
12 Karachi             16,617,644
13 Buenos Aires        15,180,176
14 Kolkata             14,864,919
15 Istanbul            14,163,989
16 Chongqing           13,331,579
17 Lagos               13,122,829
18 Manila              12,946,263
19 Rio de Janeiro      12,902,306
20 Guangzhou           12,458,130

In [20]:
import sqlite3

# Define the main function
def main():
    # Create the menu choice option
    choice = 0
    
    # Connect to the cities.db
    conn = sqlite3.connect("cities.db")
    
    # Get a cursor for the cities.db
    cur = conn.cursor()
    
    # Allow the user to input a menu choice for the cities.db
    while choice != 8:
        choice = get_menu_choice()
        execute_choice(choice, cur)
        
    # Close the connection to the cities.db
    conn.close()

# Call on the display_menu function to create the menu for the user
def display_menu():
    print("                          MENU")
    print("--------------------------------------------------------")
    print("1 - Display cities sorted by population, ascending order")
    print("2 - Display cities sorted by population, descending order")
    print("3 - Display cities sorted by name")
    print("4 - Display the total population of all the cities")
    print("5 - Display the average of all the cities")
    print("6 - Display the city with the highest population")
    print("7 - Display the city with the lowest population")
    print("8 - EXIT")
    
# Define the get_menu_choice which will display the menu and ask the user for a menu choice
def get_menu_choice():
    display_menu()
    choice = int(input("Enter a choice: "))
    # Make sure the user input is valid between 1 and 8
    while choice < 1 or choice > 8:
        choice = int(input("Enter a valid choice please: "))
    return choice

# Perform the action that the user selected by defining the execute_choice function
def execute_choice(choice, cur):
    if choice == 1:
        cities_sorted_ascending(cur)
    elif choice == 2:
        cities_sorted_descending(cur)
    elif choice == 3:
        cities_sorted_by_name(cur)
    elif choice == 4:
        total_population(cur)
    elif choice == 5:
        average_population(cur)
    elif choice == 6:
        highest_population(cur)
    elif choice == 7:
        lowest_population(cur)

# Display the cities sorted by population in ascending order
def cities_sorted_ascending(cur):
    # Execute the select statement on the cities.db
    cur.execute('''SELECT CityName, Population
                   FROM Cities
                   ORDER BY Population''')
    
    # Fetch the results for the user
    results = cur.fetchall()
    
    # Display the results for the user
    print("\n Cities Sorted By Population, in Ascending Order")
    print("-------------------------------------------------")
    display_results(results)
    
# Display the cities sorted by population in descending order
def cities_sorted_descending(cur):
    # Execute the select statement on the cities.db
    cur.execute('''SELECT CityName, Population
                   FROM Cities
                   ORDER BY Population DESC''')
    
    # Fetch the results for the user
    results = cur.fetchall()
    
    # Display the results for the user
    print("\n Cities Sorted By Population, in Descending Order")
    print("-------------------------------------------------")
    display_results(results)
    
# Display the cities sorted by name
def cities_sorted_by_name(cur):
    # Execute the select statement on the cities.db
    cur.execute('''SELECT CityName, Population
                   FROM Cities
                   ORDER BY CityName''')
    
    # Fetch the results for the user
    results = cur.fetchall()
    
    # Display the results for the user
    print("\n Cities Sorted By Name")
    print("-----------------------")
    display_results(results)
    
# Display the total population of all the cities
def total_population(cur):
    # Execute the select statement on the cities.db
    cur.execute('''SELECT SUM(Population) FROM Cities''')
    
    # Fetch the results for the user
    results = cur.fetchone()
    
    # Display the results for the user
    print(f"\n Total Population of All the Cities: {results[0]:,.0f}\n")

# Display the average population of all the cities
def average_population(cur):
    # Execute the select statement on the cities.db
    cur.execute('''SELECT AVG(Population) FROM Cities''')
    
    # Fetch the results for the user
    results = cur.fetchone()
    
    # Display the results for the user
    print(f"\n Average Population: {results[0]:,.0f}\n")

# Display the city with the highest population out of all the cities
def highest_population(cur):
    # Execute the select statement on the cities.db
    cur.execute('''SELECT MAX(Population) FROM Cities''')
    
    # Fetch the results for the user
    max_results = cur.fetchone()
    
    # Get the entire row for the city with the highest population
    cur.execute('''SELECT CityName, Population FROM Cities
                    WHERE Population = ?''', (max_results[0],))
    
    # Fetch the results for the user
    results = cur.fetchone()
    
    # Display the results for the user
    print(f"\n{results[0]} has the Highest Population: {results[1]:,.0f}\n")

# Display the city with the lowest population out of all the cities
def lowest_population(cur):
    # Execute the select statement on the cities.db
    cur.execute('''SELECT MIN(Population) FROM Cities''')
    
    # Fetch the results for the user
    min_results = cur.fetchone()
    
    # Get the entire row for the city with the lowest population
    cur.execute('''SELECT CityName, Population FROM Cities
                    WHERE Population = ?''', (min_results[0],))
    
    # Fetch the results for the user
    results = cur.fetchone()
    
    # Display the results for the user
    print(f"\n{results[0]} has the Lowest Population: {results[1]:,.0f}\n")

# Define the display_results. The function displays the results from the values of the SELECT statement
def display_results(results):
    print(f'{"City":20}{"Population"}')
    for row in results:
        print(f'{row[0]:20}{row[1]:,.0f}')
    print()
    
# Execute the main function
if __name__ == '__main__':
    main()

                          MENU
--------------------------------------------------------
1 - Display cities sorted by population, ascending order
2 - Display cities sorted by population, descending order
3 - Display cities sorted by name
4 - Display the total population of all the cities
5 - Display the average of all the cities
6 - Display the city with the highest population
7 - Display the city with the lowest population
8 - EXIT
Enter a choice: 1

 Cities Sorted By Population, in Ascending Order
-------------------------------------------------
City                Population
Guangzhou           12,458,130
Rio de Janeiro      12,902,306
Manila              12,946,263
Lagos               13,122,829
Chongqing           13,331,579
Istanbul            14,163,989
Kolkata             14,864,919
Buenos Aires        15,180,176
Karachi             16,617,644
Dhaka               17,598,228
New York            18,593,220
Cairo               18,771,769
Osaka               20,237,645
Beijing             20,383,994
Mexico City         20,998,543
Mumbai              21,042,538
Sao Paulo           21,066,245
Shanghai            23,740,778
Delhi               25,703,168
Tokyo               38,001,000

                          MENU
--------------------------------------------------------
1 - Display cities sorted by population, ascending order
2 - Display cities sorted by population, descending order
3 - Display cities sorted by name
4 - Display the total population of all the cities
5 - Display the average of all the cities
6 - Display the city with the highest population
7 - Display the city with the lowest population
8 - EXIT
Enter a choice: 4

 Total Population of All the Cities: 371,724,963

                          MENU
--------------------------------------------------------
1 - Display cities sorted by population, ascending order
2 - Display cities sorted by population, descending order
3 - Display cities sorted by name
4 - Display the total population of all the cities
5 - Display the average of all the cities
6 - Display the city with the highest population
7 - Display the city with the lowest population
8 - EXIT
Enter a choice: 8